2025-09-25 09:27:33,095 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/logging/my_first_django/my_first_django/settings.py changed, reloading.
2025-09-25 09:27:34,044 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-09-25 09:38:35,191 [INFO] shopapp.views: Rendering shop index
2025-09-25 09:38:40,975 [INFO] shopapp.views: Rendering shop index
2025-09-25 09:38:44,100 [WARNING] django.request: Not Found: /favicon.ico
2025-09-25 09:38:57,685 [WARNING] django.request: Not Found: /favicon.ico
2025-09-25 09:41:10,894 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/logging/my_first_django/my_first_django/settings.py changed, reloading.
2025-09-25 09:41:12,440 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-09-25 09:42:56,506 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/logging/my_first_django/my_first_django/settings.py changed, reloading.
2025-09-25 10:37:56,378 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-09-25 10:38:38,167 [INFO] shopapp.views: Rendering shop index
2025-09-25 10:38:38,418 [WARNING] django.request: Not Found: /favicon.ico
2025-09-25 10:41:17,023 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/logging/my_first_django/my_first_django/settings.py changed, reloading.
2025-09-25 10:41:21,415 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-09-25 10:54:02,008 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-09-25 10:54:08,892 [INFO] shopapp.views: Rendering shop index
2025-09-25 14:01:25,487 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-09-25 14:01:35,460 [INFO] shopapp.views: Rendering shop index
2025-09-25 19:18:39,168 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 18:53:35,905 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 18:53:57,364 [INFO] shopapp.views: Rendering shop index
2025-10-01 18:54:00,286 [INFO] shopapp.views: Rendering shop index
2025-10-01 19:02:29,616 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 201, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/myauth/views.py", line 48, in get_object
    print(f" текущий пользователь {self.request.user.profile.pk}\n {self.request.user}")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'profile'
2025-10-01 19:03:15,837 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 201, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/myauth/views.py", line 48, in get_object
    print(f" текущий пользователь {self.request.user.profile.pk}\n {self.request.user}")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 534, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
2025-10-01 19:13:10,019 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/my_first_django/settings.py changed, reloading.
2025-10-01 19:13:12,105 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:17:17,137 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/my_first_django/settings.py changed, reloading.
2025-10-01 19:17:18,883 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:18:58,635 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/my_first_django/settings.py changed, reloading.
2025-10-01 19:19:00,169 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:22:35,423 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/my_first_django/settings.py changed, reloading.
2025-10-01 19:22:37,587 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:24:16,439 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/my_first_django/settings.py changed, reloading.
2025-10-01 19:24:17,898 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:26:29,115 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-01 19:26:30,852 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:27:13,919 [INFO] shopapp.views: Rendering shop index
2025-10-01 19:27:14,268 [WARNING] django.request: Not Found: /favicon.ico
2025-10-01 19:31:09,868 [INFO] shopapp.views: Rendering shop index
2025-10-01 19:34:35,435 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/myauth/views.py changed, reloading.
2025-10-01 19:34:36,964 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:35:16,729 [WARNING] django.request: Not Found: /myauth/get/
2025-10-01 19:35:35,804 [WARNING] django.request: Not Found: /myauth/get/coocki/
2025-10-01 19:37:01,057 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/my_first_django/settings.py changed, reloading.
2025-10-01 19:37:02,071 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:38:49,013 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/myauth/views.py changed, reloading.
2025-10-01 19:38:51,041 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:39:06,366 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/myauth/views.py changed, reloading.
2025-10-01 19:39:07,903 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:40:16,989 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/myauth/views.py changed, reloading.
2025-10-01 19:40:18,456 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:42:05,588 [INFO] shopapp.views: Rendering shop index
2025-10-01 19:43:55,843 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-01 19:43:57,350 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:44:14,943 [INFO] shopapp.views: Rendering shop index
2025-10-01 19:53:22,745 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-01 19:53:24,228 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:54:26,625 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-01 19:54:27,889 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:56:21,815 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-01 19:56:24,194 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:57:34,620 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Zver_proga/Modul_19/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-01 19:57:36,176 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-01 19:57:57,782 [WARNING] django.request: Not Found: /favicon.ico
2025-10-02 14:02:58,667 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 14:40:50,584 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:51:28,358 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 14:51:30,022 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 14:52:21,954 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-02 14:52:23,429 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 14:52:54,439 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:55:56,865 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 14:55:58,617 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 14:58:23,967 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:58:25,179 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:58:25,844 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:58:26,471 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:58:27,106 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:58:27,669 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:58:28,179 [INFO] shopapp.views: Rendering shop index
2025-10-02 14:58:28,739 [INFO] shopapp.views: Rendering shop index
2025-10-02 15:00:31,393 [INFO] shopapp.views: Rendering shop index
2025-10-02 15:07:32,068 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 21: 'cache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2025-10-02 15:07:32,734 [WARNING] django.request: Not Found: /favicon.ico
2025-10-02 15:07:35,055 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 21: 'cache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2025-10-02 15:08:07,905 [INFO] shopapp.views: Rendering shop index
2025-10-02 15:09:31,832 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'cache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2025-10-02 15:11:40,256 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'cache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2025-10-02 15:25:08,432 [WARNING] django.request: Not Found: /favicon.ico
2025-10-02 15:25:47,404 [INFO] shopapp.views: Rendering shop index
2025-10-02 16:10:12,389 [WARNING] django.request: Not Found: /favicon.ico
2025-10-02 16:10:13,686 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'cache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2025-10-02 16:10:33,001 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'cache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2025-10-02 16:38:19,976 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 16:38:21,527 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 16:41:59,594 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 16:42:00,702 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 16:52:48,385 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 16:52:49,842 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 17:19:12,175 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 17:19:14,212 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 17:45:31,025 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 201, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/myauth/views.py", line 51, in get_object
    print(f" текущий пользователь {self.request.user.profile.pk}\n {self.request.user}")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'profile'
2025-10-02 17:49:49,660 [INFO] shopapp.views: Rendering shop index
2025-10-02 17:52:01,995 [INFO] shopapp.views: Rendering shop index
2025-10-02 17:59:09,929 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/blogapp/admin.py changed, reloading.
2025-10-02 17:59:11,503 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 17:59:59,216 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/blogapp/admin.py changed, reloading.
2025-10-02 18:00:00,757 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 18:03:29,109 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/myauth/views.py changed, reloading.
2025-10-02 18:03:30,261 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 18:16:08,876 [WARNING] django.request: Not Found: /myauth/users/2
2025-10-02 18:17:51,353 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/myauth/views.py changed, reloading.
2025-10-02 18:17:52,604 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 18:48:31,628 [WARNING] django.request: Not Found: /shop/orders/2/
2025-10-02 18:49:31,320 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:01:47,351 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:01:48,833 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:09:14,912 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:09:16,684 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:13:18,450 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:13:20,127 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:17:49,828 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:17:51,250 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:18:06,423 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 201, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/myauth/views.py", line 51, in get_object
    print(f" текущий пользователь {self.request.user.profile.pk}\n {self.request.user}")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'profile'
2025-10-02 19:18:12,746 [ERROR] django.request: Internal Server Error: /myauth/about-me/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 201, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/myauth/views.py", line 51, in get_object
    print(f" текущий пользователь {self.request.user.profile.pk}\n {self.request.user}")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/utils/functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'profile'
2025-10-02 19:36:54,623 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:36:56,044 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:37:23,711 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:37:25,201 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:38:12,863 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:38:14,194 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:38:55,648 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:38:56,709 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:41:16,958 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:41:18,173 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 19:44:37,304 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 19:44:39,701 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 21:48:56,475 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 21:48:58,654 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 21:51:11,325 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-02 21:51:12,879 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 21:54:04,759 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 21:54:06,925 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 22:04:21,306 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 22:04:23,555 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 22:37:05,618 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 22:37:07,928 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 22:40:52,132 [INFO] shopapp.views: Rendering shop index
2025-10-02 22:40:52,253 [ERROR] django.request: Internal Server Error: /shop/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 108, in get
    return render(request, 'shopapp/shop-index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'users_orders_list' with no arguments not found. 1 pattern(s) tried: ['shop/users/(?P<user_id>[0-9]+)/orders/\\Z']
2025-10-02 22:53:40,407 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 22:53:44,084 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 22:59:31,684 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 22:59:32,962 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:01:33,410 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:01:35,199 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:02:05,800 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:02:06,876 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:02:18,921 [INFO] shopapp.views: Rendering shop index
2025-10-02 23:02:19,052 [ERROR] django.request: Internal Server Error: /shop/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 108, in get
    return render(request, 'shopapp/shop-index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'users_orders_list' with no arguments not found. 1 pattern(s) tried: ['shop/users/(?P<user_id>[0-9]+)/orders/\\Z']
2025-10-02 23:03:59,179 [INFO] shopapp.views: Rendering shop index
2025-10-02 23:03:59,283 [ERROR] django.request: Internal Server Error: /shop/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 108, in get
    return render(request, 'shopapp/shop-index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'users_orders_list' with no arguments not found. 1 pattern(s) tried: ['shop/users/(?P<user_id>[0-9]+)/orders/\\Z']
2025-10-02 23:04:08,931 [INFO] shopapp.views: Rendering shop index
2025-10-02 23:04:09,025 [ERROR] django.request: Internal Server Error: /shop/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 108, in get
    return render(request, 'shopapp/shop-index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'users_orders_list' with no arguments not found. 1 pattern(s) tried: ['shop/users/(?P<user_id>[0-9]+)/orders/\\Z']
2025-10-02 23:04:28,854 [INFO] shopapp.views: Rendering shop index
2025-10-02 23:05:26,326 [INFO] shopapp.views: Rendering shop index
2025-10-02 23:05:31,879 [WARNING] django.request: Not Found: /
2025-10-02 23:05:46,088 [INFO] shopapp.views: Rendering shop index
2025-10-02 23:05:50,440 [WARNING] django.request: Not Found: /shop/c
2025-10-02 23:06:21,690 [INFO] shopapp.views: Rendering shop index
2025-10-02 23:10:07,659 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:10:09,041 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:12:04,369 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:12:05,400 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:13:13,221 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:13:14,486 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:14:25,584 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:14:26,939 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:21:02,036 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:21:03,318 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:25:29,434 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:25:30,878 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:26:05,194 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-02 23:26:06,434 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-02 23:37:05,342 [INFO] shopapp.views: Rendering shop index
2025-10-02 23:51:57,996 [WARNING] django.request: Not Found: /shop/users/6/orders/
2025-10-02 23:52:20,535 [WARNING] django.request: Not Found: /shop/users/7/orders/
2025-10-02 23:52:29,021 [WARNING] django.request: Not Found: /shop/users/2/orders/
2025-10-03 00:02:37,519 [INFO] shopapp.views: Rendering shop index
2025-10-03 00:02:40,613 [INFO] shopapp.views: Rendering shop index
2025-10-03 00:02:41,273 [INFO] shopapp.views: Rendering shop index
2025-10-03 00:04:51,059 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 00:04:52,176 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 00:07:07,526 [ERROR] django.request: Internal Server Error: /shop/users/3/orders/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 489, in parse
    raise self.error(token, e)
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 705, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/template/base.py", line 615, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'capitalize'
2025-10-03 00:13:00,542 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 00:13:01,676 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 14:37:31,929 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 14:37:35,246 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 14:39:11,591 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-03 14:39:13,304 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 14:39:15,019 [INFO] shopapp.views: Rendering shop index
2025-10-03 14:39:19,882 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 14:39:36,160 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 14:40:47,600 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 14:40:50,027 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 14:40:56,075 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 15:42:28,113 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 15:42:31,426 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 15:43:40,158 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 15:43:42,225 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 15:45:34,117 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 15:45:36,286 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 15:48:19,605 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 15:48:22,167 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 16:39:33,563 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 16:39:37,284 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 16:40:02,164 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:40:26,096 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 16:40:27,920 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 16:40:30,387 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:41:03,424 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:41:13,905 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:41:17,460 [ERROR] django.request: Internal Server Error: /shop/products/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 251, in get
    return JsonResponse({"products": products_data})
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'products_data' where it is not associated with a value
2025-10-03 16:41:17,788 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:41:19,689 [ERROR] django.request: Internal Server Error: /shop/products/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 251, in get
    return JsonResponse({"products": products_data})
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'products_data' where it is not associated with a value
2025-10-03 16:41:21,237 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:41:23,089 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:41:27,748 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:41:41,359 [ERROR] django.request: Internal Server Error: /shop/products/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 251, in get
    return JsonResponse({"products": products_data})
                                     ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'products_data' where it is not associated with a value
2025-10-03 16:43:42,682 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 16:43:44,022 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 16:43:45,251 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:43:47,497 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:44:00,780 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 16:44:02,365 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 16:44:03,571 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:44:38,844 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 16:44:40,442 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 16:49:32,002 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 16:49:33,278 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 16:49:39,706 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:49:44,251 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 16:57:38,933 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 16:57:42,437 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 17:02:50,120 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 17:02:51,991 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 17:05:28,333 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-03 17:05:29,670 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 17:06:03,863 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 17:07:19,493 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 18:00:51,151 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 18:00:53,146 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 18:47:01,364 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 18:47:03,230 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 18:47:09,002 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 18:47:22,753 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 18:47:37,117 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 18:49:54,271 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 18:49:56,938 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 18:55:13,812 [WARNING] django.request: Not Found: /myauth/groups/
2025-10-03 18:58:53,475 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-03 18:58:55,287 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 18:58:58,876 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 188, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 18:59:00,556 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 188, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:01:48,963 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:01:50,343 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:06:05,355 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:06:06,599 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:06:09,383 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 188, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:08:10,927 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:08:12,188 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:08:13,899 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 188, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:09:06,274 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/serializers.py changed, reloading.
2025-10-03 19:09:07,670 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:09:13,625 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 19:09:15,351 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 19:09:25,881 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 188, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:20:20,285 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/serializers.py changed, reloading.
2025-10-03 19:20:21,742 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:27:42,940 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:27:44,744 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:27:45,563 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:27:46,687 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:28:19,316 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:28:20,374 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:28:26,023 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 19:28:27,548 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 19:29:18,087 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:29:19,280 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:31:04,016 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:31:05,121 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:33:23,880 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:33:25,190 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:33:34,327 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:33:35,681 [ERROR] django.request: Internal Server Error: /shop/users/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:36:51,084 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 19:50:50,993 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-03 19:50:52,331 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:50:52,950 [WARNING] django.request: Not Found: /shop/users/orders/export/
2025-10-03 19:51:21,987 [WARNING] django.request: Not Found: /shop/users/2/orders/export/
2025-10-03 19:53:25,316 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-03 19:53:26,554 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:53:28,584 [ERROR] django.request: Internal Server Error: /shop/users/3/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:54:29,388 [ERROR] django.request: Internal Server Error: /shop/users/3/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:57:28,521 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:57:29,950 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:57:30,881 [ERROR] django.request: Internal Server Error: /shop/users/3/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:57:32,115 [ERROR] django.request: Internal Server Error: /shop/users/3/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:58:34,448 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 19:58:36,052 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:58:36,938 [ERROR] django.request: Internal Server Error: /shop/users/3/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 190, in get_queryset
    self.owner = get_object_or_404(User, id=self.kwargs["user_id"])
                                            ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'user_id'
2025-10-03 19:59:50,161 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-03 19:59:51,165 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 19:59:58,389 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:04:44,637 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:04:45,884 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:04:49,219 [ERROR] django.request: Internal Server Error: /shop/users/3/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 274, in get
    user = get_object_or_404(User, id=self.request["pk"])
                                      ~~~~~~~~~~~~^^^^^^
TypeError: 'WSGIRequest' object is not subscriptable
2025-10-03 20:04:58,075 [ERROR] django.request: Internal Server Error: /shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 274, in get
    user = get_object_or_404(User, id=self.request["pk"])
                                      ~~~~~~~~~~~~^^^^^^
TypeError: 'WSGIRequest' object is not subscriptable
2025-10-03 20:05:35,829 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:05:37,363 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:05:38,847 [ERROR] django.request: Internal Server Error: /shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py", line 274, in get
    user = get_object_or_404(User, id=self.request["user_id"])
                                      ~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'WSGIRequest' object is not subscriptable
2025-10-03 20:06:52,961 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:06:54,370 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:06:55,658 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:07:20,610 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:08:26,951 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:09:20,368 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/serializers.py changed, reloading.
2025-10-03 20:09:21,703 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:09:23,038 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:09:35,072 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:09:39,446 [WARNING] django.request: Not Found: /shop/users/6/orders/export/
2025-10-03 20:09:46,058 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:11:51,247 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:11:52,744 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:11:55,720 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:12:00,436 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:12:13,613 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:14:03,139 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/urls.py changed, reloading.
2025-10-03 20:14:04,263 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:14:11,019 [ERROR] django.request: Internal Server Error: /shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserOrdersDataExportView.get() got an unexpected keyword argument 'pk'
2025-10-03 20:14:13,820 [ERROR] django.request: Internal Server Error: /shop/users/1/orders/export/
Traceback (most recent call last):
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seriy-pa/PycharmProjects/python_django/.venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserOrdersDataExportView.get() got an unexpected keyword argument 'pk'
2025-10-03 20:14:29,531 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:14:50,109 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:17:19,235 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:22:11,196 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:22:17,862 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:31:25,183 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:31:26,643 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:31:34,329 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:31:52,713 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:32:23,905 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:32:25,965 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:32:28,752 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:33:29,027 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:33:30,785 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:33:33,448 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:41:31,633 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:41:32,789 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:41:35,511 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:43:26,380 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:43:27,479 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-03 20:44:19,322 [WARNING] django.request: Not Found: /favicon.ico
2025-10-03 20:47:01,271 [INFO] django.utils.autoreload: /home/seriy-pa/PycharmProjects/python_django/Django_Cache/Homework/my_first_django/shopapp/views.py changed, reloading.
2025-10-03 20:47:02,949 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 20:14:00,338 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 20:15:39,343 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-07 08:26:52,709 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-07 08:36:26,362 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-07 08:36:43,939 [WARNING] django.request: Not Found: /
2025-10-07 08:36:49,024 [INFO] shopapp.views: Rendering shop index
2025-10-07 16:30:00,101 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-07 16:35:43,250 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-07 16:36:13,959 [WARNING] django.request: Not Found: /favicon.ico
2025-10-07 16:36:23,375 [WARNING] django.request: Not Found: /
2025-10-07 16:36:39,987 [INFO] shopapp.views: Rendering shop index
2025-10-07 16:36:46,264 [INFO] shopapp.views: Rendering shop index
2025-10-08 11:29:16,855 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-08 11:29:37,843 [WARNING] django.request: Not Found: /
2025-10-08 11:34:01,401 [WARNING] django.request: Not Found: /favicon.ico
2025-10-08 11:34:12,093 [WARNING] django.request: Not Found: /favicon.ico
2025-10-09 17:01:41,348 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-09 17:01:52,591 [WARNING] django.request: Not Found: /
2025-10-09 17:02:32,060 [WARNING] django.request: Not Found: /favicon.ico
